version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong@Pass123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./Goals
      dockerfile: Dockerfile
    ports:
      - "5026:5026"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5026
    depends_on:
      - mssql
    networks:
      - app-network

  frontend:
    build:
      context: ./GoalsFront
      dockerfile: Dockerfile   # Bu Dockerfile, az önce verdiğimiz "Node→Nginx" multi-stage Dockerfile olmalı
    ports:
      - "4200:80"             # Host 4200’ü container 80’e yönlendiriyoruz
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
