version: "3.9"

services:
  backend:
    build:
      context: ./Goals
      dockerfile: Dockerfile
    ports:
      - "5026:5026"
    networks:
      - app-network

  frontend:
    build:
      context: ./GoalsFront
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    networks:
      - app-network
    mem_limit: 2g

networks:
  app-network:
    driver: bridge
