version: "3.9"

services:
  backend:
    image: ${DOCKER_USERNAME:-yourusername}/fintech-backend:latest
    ports:
      - "5026:5026"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5026
    networks:
      - app-network

  frontend:
    image: ${DOCKER_USERNAME:-yourusername}/fintech-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge